name: Bug Report
description: File a bug report
title: "[Bug] "
labels: ["bug", "triage"]
assignees: []
body:
  - type: textarea
    attributes:
    label: Summary
    validations:
    required: true
  - type: textarea
    attributes:
    label: Steps to reproduce
    value: 1. ...
  - type: textarea
    attributes:
    label: Expected behaviour
  - type: textarea
    attributes:
    label: Actual behaviour
  - type: textarea
    attributes:
    label: Elixir/Erlang version
    description: "`elixir -v`"
    validations:
    required: true
  - type: textarea
    attributes:
    label: Flop and Ecto versions
    description: "`mix deps | grep 'flop\\| ecto \\|ecto_sql'`"
    validations:
    required: true
  - type: textarea
    attributes:
    label: Additional context
